# Generated by Django 4.1.1 on 2022-09-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_answers_options_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Выберите категорию', max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='answers',
            name='correct_answer',
            field=models.BooleanField(blank=True, default=False, verbose_name='Правильность ответа'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(help_text='Выберите вопрос', on_delete=django.db.models.deletion.CASCADE, to='tests.questions', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='test_title',
            field=models.ForeignKey(help_text='Выберите тест', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.testsbase', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_text',
            field=models.TextField(max_length=1000, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(help_text='Выберите тест', on_delete=django.db.models.deletion.CASCADE, to='tests.testsbase', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='testsbase',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию', null=True, on_delete=django.db.models.deletion.PROTECT, to='tests.categories', verbose_name='Категория'),
        ),
    ]
