# Generated by Django 4.1.1 on 2022-09-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_categories_alter_answers_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsbase',
            name='description',
            field=models.TextField(help_text='Введите описание теста', max_length=300, null=True, verbose_name='Краткое описание теста'),
        ),
    ]
