# Generated by Django 4.1.1 on 2022-09-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testsbase_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsbase',
            name='amount_questions',
            field=models.IntegerField(help_text='Введите количество вопросов', null=True, verbose_name='Количество вопросов'),
        ),
    ]
