# Generated by Django 4.1.1 on 2022-12-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer_photo',
        ),
    ]
