# Generated by Django 4.1.3 on 2022-12-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_recordanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordanswers',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='recordanswers',
            name='is_correct',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.answers')),
                ('answer_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.recordanswers')),
            ],
        ),
    ]
